#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    b=[]
    while n>0:
        b.append(str(n%2))
        n=n//2
    a="".join((b[::-1])).split('0')
    print(max([i.count('1') for i in a]))
