#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    hs,ls=[scores[0]]*n,[scores[0]]*n

    for i in range(n):
        if hs[i-1]<scores[i]:
            hs[i]=scores[i]
        else :
            hs[i]=hs[i-1]
    for i in range(n):
        if ls[i-1]>scores[i]:
            ls[i]=scores[i]
        else :
            ls[i]=ls[i-1]

    return len(set(hs))-1,len(set(ls))-1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
    
    
    
#######################################################################
갱신되는 count만 구하려면 아래처럼 하면 간결함 

def breaking_records(score):
    min = max = score[0]
    min_count = max_count = 0
    for i in score[1:]:
        if i > max:
            max_count += 1
            max = i
        if i < min:
            min_count += 1
            min = i
    return max_count, min_count
    
   
