#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    result,step=0,0
    # for i in path:
    #     if i=='U':
    #         step+=1
    #     else :
    #         step-=1       
    #     if step==0 and i=='U':
    #         result+=1
    # return result

    for i in path:
        step+=1 if i=='U' else -1
        result+= step==0 and i=='U'
    return result  
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
